export const ADD_USER_MESSAGE = 'ADD_USER_MESSAGE';
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';
export const ADD_MESSAGES = 'ADD_MESSAGES';
export const SET_ORDER_ID = 'SET_ORDER_ID';
export const SET_NOTIFICATION_DATA = 'SET_NOTIFICATION_DATA';
export const SET_SELECTED_RIDER = 'SET_SELECTED_RIDER';
export const RATING_API_SUCCESS = 'RATING_API_SUCCESS';
export const RATING_API_FAIL = 'RATING_API_FAIL';
export const UPDATE_RATING_LOADING = 'UPDATE_RATING_LOADING';
export const ORDER_COMPLETE_API_SUCCESS = 'ORDER_COMPLETE_API_SUCCESS';
export const ORDER_COMPLETE_API_FAIL = 'ORDER_COMPLETE_API_FAIL';
export const SET_ORDER_STATUS = 'SET_ORDER_STATUS';
export const SET_TRACKING_LOCATION = 'SET_TRACKING_LOCATION';

export const CANCEL_ORDER_API_SUCCESSFULL = 'CANCEL_ORDER_API_SUCCESSFULL';
export const CANCEL_ORDER_API_FAIL = 'CANCEL_ORDER_API_FAIL';
