export const UPDATE_PROMOS = 'UPDATE_PROMOS';
export const PROMO_API_FAIL = 'PROMO_API_FAIL';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';

export const LOGIN_USER_NAME = 'LOGIN_USER_NAME';
export const LOGIN_USER_EMAIL = 'LOGIN_USER_EMAIL';
export const LOGIN_USER_PHONE_NUMBER = 'LOGIN_USER_PHONE_NUMBER';
export const LOGIN_USER_COUNTRY_CODE = 'LOGIN_USER_COUNTRY_CODE';
export const LOGIN_USER_SOCIALMEDIA_TYPE = 'LOGIN_USER_SOCIALMEDIA_TYPE';
export const LOGIN_USER_SOCIALMEDIA_ID = 'LOGIN_USER_SOCIALMEDIA_ID';
export const USER_SELECTED_LANGUAGE = 'USER_SELECTED_LANGUAGE';