export const SELECT_PICKUP_LOCATION = 'SELECT_PICKUP_LOCATION';
export const SELECT_DETINATION_LOCATION = 'SELECT_DETINATION_LOCATION';
export const SELECT_ORDER_FARE = 'SELECT_ORDER_FARE';
export const SELECT_ORDER_DISTANCE = 'SELECT_ORDER_DISTANCE';
export const SELECT_ORDER_NOTE = 'SELECT_ORDER_NOTE';
