export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const NOTIFICATION_API_SUCCESS = 'NOTIFICATION_API_SUCCESS';
export const NOTIFICATION_API_FAIL = 'NOTIFICATION_API_FAIL';
export const NOTIFICATION_LOADING = 'NOTIFICATION_LOADING';
