export const LOGIN_USER = 'LOGIN_USER';
export const USER_LOGGEDIN = 'USER_LOGGEDIN';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';

export const LOGIN_USER_NAME = 'LOGIN_USER_NAME';
export const LOGIN_USER_EMAIL = 'LOGIN_USER_EMAIL';
export const LOGIN_USER_PHONE_NUMBER = 'LOGIN_USER_PHONE_NUMBER';
export const LOGIN_USER_COUNTRY_CODE = 'LOGIN_USER_COUNTRY_CODE';
export const LOGIN_USER_SOCIALMEDIA_TYPE = 'LOGIN_USER_SOCIALMEDIA_TYPE';
export const LOGIN_USER_SOCIALMEDIA_ID = 'LOGIN_USER_SOCIALMEDIA_ID';
export const USER_SELECTED_LANGUAGE = 'USER_SELECTED_LANGUAGE';
export const SHOW_FLOATING_BUTTONS = 'SHOW_FLOATING_BUTTONS';
export const INIT_API_SUCCESS = 'INIT_API_SUCCESS';
export const INIT_API_FAIL = 'INIT_API_FAIL';
